<?php

namespace AppBundle\Repository;

/**
 * AutoResponseOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoResponseOfferRepository extends \Doctrine\ORM\EntityRepository
{
}
