<?php

namespace AppBundle\Repository;

/**
 * RedeemedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedeemedRepository extends \Doctrine\ORM\EntityRepository
{
}
